### PR TITLE
Docker-based local development environment + Clean up rustfmt.toml

### LINKED ISSUE #37: Failed to compile master on MacOS
#### Version Information:

* Version: 0.11.1

Macbook running Catalina 10.15.5, rustc 1.44.1 (c7087fe00 2020-06-17)
#### Description:
 

Compiling fails, giving:
```
 Compiling horust v0.1.1 (/Users/t0mgs/IdeaProjects/Horust)
error[E0432]: unresolved imports `libc::prctl`, `libc::PR_SET_CHILD_SUBREAPER`

src/horust/mod.rs:14:12
   |
14 | use libc::{prctl, PR_SET_CHILD_SUBREAPER};
   |            ^^^^^  ^^^^^^^^^^^^^^^^^^^^^^ no `PR_SET_CHILD_SUBREAPER` in the root
   |            |
   |            no `prctl` in the root

error[E0425]: cannot find function `execvpe` in module `nix::unistd`
   --> src/horust/runtime/process_spawner.rs:149:18
    |
149 |     nix::unistd::execvpe(program_name.as_ref(), arg_cptr.as_ref(), env_cptr.as_ref())?;
    |                  ^^^^^^^ help: a function with a similar name exists: `execve`
    | 
   ::: /Users/t0mgs/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.16.1/src/unistd.rs:734:1
    |
734 | pub fn execve(path: &CStr, args: &[&CStr], env: &[&CStr]) -> Result<Void> {
    | ------------------------------------------------------------------------- similarly named function `execve` defined here

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0425, E0432.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `horust`.
```

Haven't actually figured out what these deps are, just wanted to persist this if anyone else has the same issue.
@FedericoPonzi gettin' late round these parts, if you can take a look that would be great.

### PR DESCRIPTION
**Pull request by tomgs**
This fixes #37 and #42, by creating a container-based workflow for local development, and cleaning up unstable features in `rustfmt.toml` - which will reduce CI warnings.

An explanation of the workflow can be found in the diff of `CONTRIBUTING.md`, but I'm pasting it here too:

## Local development using a container

If you'd like to skip all the bells and whistles of setting up the project, you can get up and running quickly using an
"All-In-One" Docker container. It's a wrapper around Horust that enables you to compile it and all of its dependencies,
and then work off the binary instead of compiling yourself.

The `Makefile` contains a set of commands intended to scaffold an AIO container from scratch.
 
Just run `make dargo-prep` inside the project's root folder.
This will:

1. Create a Docker image with a pre-determined working directory
2. Run an (interactive / long-running) container off that image, with the local Horust project folder bind-mounted to the working directory
3. Compile Horust and all its dependencies inside the container, using the local folder as storage for the cache
4. Compile test dependencies and fill a few more caches (using `cargo test` and `cargo check`)

When the Makefile target finishes, you will have a running container on your machine that you can compile Horust in.
That container allows you to take advantage of `rustc`'s incremental compilation, without compiling locally.

You can now run `make dargo COMMAND=X`, where `X` is some `cargo` command (like `build` / `test` / `check`) to run `cargo`
inside that container with command `X`.

If you like to go for maximum ergonomics, run the following command (swapping `~/.bashrc` for `~/.zshrc` or wherever you keep your shell stuff):
 
```bash
echo 'dargo(){ make dargo COMMAND=$1}' >> ~/.bashrc
source ~/.bashrc
```

This will now enable you to run `dargo X` instead of `make dargo COMMAND=X`, to get a more `cargo`-like feel while using the container.
Try running `dargo check` to see how if feels!

### Container-based development example

Just to make sure everything is clear, let's run a step-by-step mini tutorial on developing in container-based workflow "mode":

1. Clone the repo to your local machine:
```shell 
git clone https://github.com/FedericoPonzi/Horust.git`
cd Horust
```
2. Create the AIO container (can take a while):
```shell
make dargo-prep
``` 
3. Add "alias" to `make dargo COMMAND=X`:
```shell
echo 'dargo(){ make dargo COMMAND=$1}' >> ~/.bashrc
source ~/.bashrc
```
4. Make some changes to a source file.
5. Run the following to test your changes:
```shell
dargo test
```

### CODE REVIEW

**Comment by tomgs** [comment]
Currently failing at:

```
t0mgs@Toms-MacBook-Air Horust % make dlocal-build
Building an Horust image for local development
docker build -t "local"/"horust" -f localdev/Dockerfile --build-arg GIT_COMMIT="edfbeaee6d56d2121a445ea6e249d471d62aac4f" --build-arg GIT_BRANCH="horust-macos-baby"  .
Sending build context to Docker daemon   1.19MB
Step 1/22 : FROM rust:1.42 as builder
 ---> ec5ed72f5852
Step 2/22 : WORKDIR /usr/src/myapp
 ---> Using cache
 ---> 6874ea500e0e
Step 3/22 : ARG CARGO_PARAMS
 ---> Using cache
 ---> 2b4f1483cb2c
Step 4/22 : ARG GIT_COMMIT
 ---> Using cache
 ---> 401359025760
Step 5/22 : ARG GIT_BRANCH
 ---> Using cache
 ---> 1cbfcba1787f
Step 6/22 : ARG IMAGE_NAME
 ---> Using cache
 ---> 97c5c7540bcd
Step 7/22 : COPY localdev/dummy.rs Cargo.toml Cargo.lock ./
 ---> Using cache
 ---> 93e5d79fcb75
Step 8/22 : RUN sed -i 's^src/main.rs^localdev/dummy.rs^' Cargo.toml
 ---> Using cache
 ---> b59db48f1f66
Step 9/22 : RUN echo "Running cargo build with dummy program to build all deps: $CARGO_PARAMS" && cargo build $CARGO_PARAMS
 ---> Running in 08c69bf7c68f
Running cargo build with dummy program to build all deps: 
    Updating crates.io index
 Downloading crates ...
  Downloaded reqwest v0.10.1
...
...
...
   Compiling reqwest v0.10.1
   Compiling horust v0.1.1 (/usr/src/myapp)
error: couldn't read localdev/dummy.rs: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile `horust`.

To learn more, run the command again with --verbose.
```

I'm mixing something with the paths, but I'm too tired to figure out what it is exactly. Back tomorrow. :)

File: localdev/Dockerfile [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+RUN sed -i 's^src/main.rs^localdev/dummy.rs^' Cargo.toml
+RUN echo "Running cargo build with dummy program to build all deps: $CARGO_PARAMS" && cargo build $CARGO_PARAMS
+# Now switch back to the main problem before actually creating the Horust binary
+RUN sed -i 's^localdev/dummy.rs^src/main.rs^' Cargo.toml
+# Get everything else into the conatiner
+COPY ../ .
+# And now build without re-compiling all the things! Profit!
+RUN echo "Running cargo build with actual Rust code to build all deps: $CARGO_PARAMS" && cargo build $CARGO_PARAMS
+
+FROM debian:buster-slim
```
Comment (FedericoPonzi) [inline localdev/Dockerfile:23]: You probably don't need this second step. I think the ux here should be `make dlocal x`, with x = a command for cargo (so `build`, `build --release`, `test` etc..)

File: localdev/dummy.rs [hunk 2]
```diff
@@ -0,0 +1,2 @@
+// Dummy file used for local development build
+fn main() {}
```
Comment (FedericoPonzi) [inline localdev/dummy.rs:2]: this can probably live in the dockerfile itself. Something like `echo 'fn main() {}' > dummy.rs`

File: localdev/Dockerfile [hunk 3]
```diff
@@ -0,0 +1,33 @@
+## This Dockerfile is used for building Horust in a conatiner while developing locally.
+## It follows https://blog.mgattozzi.dev/caching-rust-docker-builds/ AND SHOULD NOT BE USED IN PRODUCTION
+
+FROM rust:1.42 as builder
+WORKDIR /usr/src/myapp
+ARG CARGO_PARAMS
+ARG GIT_COMMIT
```
Comment (FedericoPonzi) [inline localdev/Dockerfile:7]: these are not needed for the "development" container

File: CONTRIBUTING.md [hunk 4]
```diff
@@ -60,6 +60,16 @@ make help
 
 ---
 
+## Local development using a container
+
+Horust was developed to be used inside containers. That means that it's primarily built to be used in *nix environments,
+and even more specifically in Linux and its flavours. At the time of writing, Horust fails to compile on Mac OSX due 
+to a dependency (`prctl`) that does not exist on Mac, as well as some `libc` functions that are Linux-sepcific and are
+not available on OSX.
```
Comment (FedericoPonzi) [inline CONTRIBUTING.md:68]: I would not put it in these (kind of negative) terms. I would just say that if you don't want to install / setup cargo and the project's stuff (or you cannot get to build it because you're on Macos) then you can just go with the AIO docker container wrapper

File: CONTRIBUTING.md [hunk 5]
```diff
@@ -60,6 +60,16 @@ make help
...
 ---
 
+## Local development using a container
+
+Horust was developed to be used inside containers. That means that it's primarily built to be used in *nix environments,
+and even more specifically in Linux and its flavours. At the time of writing, Horust fails to compile on Mac OSX due 
+to a dependency (`prctl`) that does not exist on Mac, as well as some `libc` functions that are Linux-sepcific and are
+not available on OSX. 
+
+To solve this issue, the [`localdev`](https://github.com/FedericoPonzi/Horust/blob/edfbeaee6d56d2121a445ea6e249d471d62aac4f/localdev#L70-L70) folder contains a small set of files that aid in creating a container-based development workflow.
```
Comment (FedericoPonzi) [inline CONTRIBUTING.md:70]: I think the link to localdev will need an update :) also, instead of explaining the problem and the solution, I think it would be better to just explain how to use this "alternative" way to work with horust

File: localdev/Dockerfile (hunk 1 above)
Comment (tomgs) [reply localdev/Dockerfile:23]: So the output is a `horust` binary that's then copied outside of the container into my local machine? Or an image with the compiled binary inside of it?

File: localdev/dummy.rs (hunk 2 above)
Comment (tomgs) [reply localdev/dummy.rs:2]: True, true. Changing.

File: localdev/Dockerfile (hunk 3 above)
Comment (tomgs) [reply localdev/Dockerfile]: Removed

**Comment by tomgs** [comment]
Ah, so `cargo fmt` fails because it wants to find that `dummy.rs` file....
How is it aware of its existence? The `[[bin]]` in the `Cargo.toml`?
I could just plop it in there, but that would be messy IMHO.
Will come back later and fix this

File: localdev/Dockerfile [hunk 6]
```diff
@@ -0,0 +1,19 @@
...
+## It follows https://blog.mgattozzi.dev/caching-rust-docker-builds/ AND SHOULD NOT BE USED IN PRODUCTION
+
+FROM rust:1.42
+WORKDIR /usr/src/myapp
+ARG CARGO_PARAMS
+# The dummy file is just used to get the deps into our project
+# Note that COPY only runs if the files it is provided has changed, otherwise the Docker cache is hit
+COPY Cargo.toml Cargo.lock ./
+# This uses the dummy Rust program to compile all deps
+RUN echo 'fn main() {}' > dummy.rs
```
Comment (FedericoPonzi) [inline localdev/Dockerfile:11]: this should be src/dummy.rs I think

File: localdev/Dockerfile (hunk 1 above)
Comment (FedericoPonzi) [reply localdev/Dockerfile]: nope nope, this docker container is used just for developing locally, so you probably want to run `cargo test` on the thing in order to build it and making sure tests are passing - so no need to actually build horust. For this reason, I think the ux would be that every parameter you pass to the container, will be passed down to cargo. So you can say `docker [..] test mycoolfeature`.

Comment (FedericoPonzi) [reply localdev/Dockerfile]: Actually, I think you could even keep this pr open for a while, try to work on the other issue, and improve this pr based on your experience developing with it. As soon as you think the workflow is fine enough, we can merge it. WDYT?

File: localdev/Dockerfile (hunk 6 above)
Comment (tomgs) [reply localdev/Dockerfile:11]: It's running inside `WORKDIR`, so it doesn't matter I think

Comment (tomgs) [reply localdev/Dockerfile:11]: Changed it to `src/dummy.rs`, and also added an empty file there to make `rustfmt` happy.

All logic is done in the `Dockerfile`, and once https://github.com/FedericoPonzi/Horust/issues/42 is fixed (and `ignore` in `rusfmt.toml` is actually used) we can get rid of the empty `dummy.rs`.

Comment (tomgs) [reply localdev/Dockerfile]: Nope, no go, now the test scripts are angry at me:

```
  Compiling horust v0.1.1 (/home/runner/work/Horust/Horust)
error[E0601]: `main` function not found in crate `horust`
##[error] --> src/dummy.rs:2:75
  |
2 | // Remove once https://github.com/FedericoPonzi/Horust/issues/42 is fixed
  |                                                                           ^ consider adding a `main` function to `src/dummy.rs`

error: aborting due to previous error
```

I'm going to scrape the logic from the `Dockerfile`. If you have a suggestion on how to not get left with a `dummy.rs` file for now lmk.

File: localdev/Dockerfile (hunk 1 above)
Comment (tomgs) [reply localdev/Dockerfile]: Hmmp. Probably a good idea, but that would mean working off of this branch.
That might make another PRs cumbersome to merge later.

What I could do is branch off this branch, work on an issue until I'm satisfied with it, merge this PR and then merge the issue later.

File: localdev/dummy.rs (hunk 2 above)
Comment (tomgs) [reply localdev/dummy.rs]: Note that I removed it from the `Dockerfile` following https://github.com/FedericoPonzi/Horust/pull/41#discussion_r456797726

File: CONTRIBUTING.md (hunk 4 above)
Comment (tomgs) [reply CONTRIBUTING.md:68]: Fixed

File: CONTRIBUTING.md (hunk 5 above)
Comment (tomgs) [reply CONTRIBUTING.md:70]: Fixed, added a comment to return back to this later once I'm 100% sure that this works and is ergonomic enough

**Comment by tomgs** [comment]
Following the comments above, the actual workflow should be something like this:

1. User clones repo
1. Assuming Docker & Rust are installed, user runs `make dlocal build`
1. Image containing Horust and all dependencies is built, since the makefile is calling `cargo build` underneath
1.  User makes some changes to the Horust source code
1. We don't want to compile all the deps again, so user runs `make dlocal run`
1. This compiles _just Horust_, by passing run to cargo
1. Output of compilation is passed to stdout and resembles normal `cargo run`

This makes an explicit assumption that just swapping `cargo build` for `cargo run` will be smart enough to not build all the deps again, which relies on the fact that `docker build` _should_ hit the cache instead of re-building all the time.

This is not actually the case, I'm afraid. Looking into https://github.com/moby/moby/issues/30081 to figure out whteher that's the issue.

File: localdev/Dockerfile (hunk 1 above)
Comment (FedericoPonzi) [reply localdev/Dockerfile]: I disagree on the merge later thing, this pr adds the dockerfile and updates the makefile, and the pr for the other feature is probably modifying just the rust code, so it should be rather easy to merge later on

Comment (tomgs) [reply localdev/Dockerfile]: Alright, let me first get this stabilized and working fast and we'll take it from there

**Comment by FedericoPonzi** [comment]
> Following the comments above, the actual workflow should be something like this:
> 
>     1. User clones repo
> 
>     2. Assuming Docker & Rust are installed, user runs `make dlocal build`

Well, probably having rust installed is suggest but not mandatory, because you can handle everything from within the docker container.

>     3. Image containing Horust and all dependencies is built, since the makefile is calling `cargo build` underneath
> 
>     4. User makes some changes to the Horust source code
> 
>     5. We don't want to compile all the deps again, so user runs `make dlocal run`
> 
>     6. This compiles _just Horust_, by passing run to cargo
> 
>     7. Output of compilation is passed to stdout and resembles normal `cargo run`
> 
> 
> This makes an explicit assumption that just swapping `cargo build` for `cargo run` will be smart enough to not build all the deps again, which relies on the fact that `docker build` _should_ hit the cache instead of re-building all the time.
> 
> This is not actually the case, I'm afraid. Looking into [moby/moby#30081](https://github.com/moby/moby/issues/30081) to figure out whteher that's the issue.

I mean, another way could be to have an interactive rust docker container running and with horust mounted as a volume in the apps folder. Then from the shall one could just treat it as your local shell and run all the commands from there (cargo build / test / run etc).

As an addendum, lately I'm never running `cargo run`, integration tests are actually easier to use for testing things.

**Comment by tomgs** [comment]
So, to recap (following our WhatsApp discussion and the comment above):

There is _some_ merit in the work I've been doing, in that it can be a replacement for the existing Dockerfile and maybe also to CI. It is not, however, the easiest/smartest way to achieve the goal we originally set out to get - which is local development using compilation inside a container.

The easiest path seems to be what you mentioned now and what I suggested earlier - adding the Horust folder as bind mount to a regular Rust container, and editing the Makefile to make compiling and running inside the container a bit more ergonomic. This will ensure the compiler cache is not invalidated (since we're using the exact same folder as local compilation, just mounted to a container), thus preventing all of the shenanigans I attempted above. Working on this now!

(p.s. haven't had this much fun with Docker in a while!)

**Comment by tomgs** [comment]
So I tried something like this:

```bash
docker build -t local:horust -f localdev/Dockerfile localdev/ && \
docker run --rm \
--name local-horust \
--user "$(id -u)":"$(id -g)" \
--mount type=bind,source="$(pwd)"/,target=/usr/src/Horust \
local:horust \
cargo build --release
```

Where the `localdev/Dockerfile` just looks like this:

```Dockerfile
FROM rust:1.42
WORKDIR /usr/src/Horust
CMD ["/bin/bash"]
```

And it compiles nicely. Now I can run it interactively so it keeps on spinning as long as I'm developing:

```bash
docker run -it -d \
--name local-horust-interactive \
--user "$(id -u)":"$(id -g)" \
--mount type=bind,source="$(pwd)"/,target=/usr/src/Horust \
local:horust
```

Which, as suspected, gives me a running container:
```bash
t0mgs@Toms-MacBook-Air Horust % docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                          PORTS               NAMES
12ccfa142dfe        local:horust        "/bin/bash"         3 seconds ago        Up 1 second                                         local-horust-interactive
```

The tricky part comes next - when I want to actually use the pre-compiled project:

```bash
docker exec 12ccfa142dfe cargo test
```

I'm getting an "Updating crates.io index" + deps download + deps compilation all over again, meaning the cache was somehow invalidated anyways.

Pushing what I have now, but still no cigar.

**Comment by tomgs** [comment]
Whoops, just figured out my problem - I actually need to run the build properly on the first interactive run, and then do the test. Give me a sec to validate

**Comment by tomgs** [comment]
So this is the final flow that worked for me:

```shell
# Build local image
docker build -t Horust -f localdev/Dockerfile localdev/

# Then run the container interactively but detached (i.e. make it long-running)
docker run -dt \
--name local-horust \
--user "$(id -u)":"$(id -g)" \
--mount type=bind,source="$(pwd)"/,target=/usr/src/Horust \
Horust

# Now we've got a container running.
# First, tell it to do a cargo build so all dependencies get built
docker exec -ti $(docker ps -a | grep Horust | cut -c1-12) cargo build

# Now we've got all the artifcats compiled inside the container.
# Now let's run the tests, just to see if the cache holds
docker exec -ti $(docker ps -a | grep Horust | cut -c1-12) cargo test
# Some test-specific crates will now be downloaded, and the tests will run.

# Now let's run the checks, also to make sure that the check holds
docker exec -ti $(docker ps -a | grep Horust | cut -c1-12) cargo check
```

Tried incorporating into the Makefile:

```make
# Docker local development tasks
## Dargo == Docker Cargo
dargo-prep: ## This runs everything neccessary to start developing locally in a container
	# Spin up a long-running rust container
	make dargo-create-container
	# Compile and cache all dependencies
	make dargo COMMAND=build
    # Compile and cache test dependencies, run tests
	make dargo COMMAND=test
	# Perform a first-sweep check, to make latter ones faster
	make dargo COMMAND=check
	# Now everything should be pretty fast:)

dargo: ## Run a cargo command inside the container
	docker exec -ti local-horust cargo $(COMMAND)

dargo-create-container: ## Create a Rust container with this folder bind-mounted to it
	@echo 'building rust image for local development'
	docker build -t horust -f localdev/Dockerfile localdev/
	@echo 'running interactive rust container for local development'
	docker run -dt \
 	--name local-horust \
 	--user "$(id -u)":"$(id -g)" \
 	--mount type=bind,source="$(pwd)"/,target=/usr/src/Horust \
 	horust
```

And `dargo-prep` doesn't work as I expect too. Will do some more tomorrow.

**Comment by tomgs** [comment]
Ah, silly me, subshells in Makefiles need `$(shell COMMAND)` to work. Seems to be working nicely now, will get the final pull request out of draft once I'm done trying to develop a feature.

**Comment by tomgs** [comment]
Working now, and if you put: `dargo(){ make dargo COMMAND=$1}` in your `.zshrc` or `.bashrc` you can do:

`dargo check`
`dargo test`
`dargo run`
`dargo build`

etc!

**Comment by tomgs** [comment]
Alright, tests are now passing and I'm pretty happy with the general thing!
I'm getting it out of draft since it works properly. Maybe we can merge @FedericoPonzi and I touch it up later as I work on actual features?

File: localdev/Dockerfile (hunk 1 above)
Comment (tomgs) [reply localdev/Dockerfile]: Take a look now

File: localdev/dummy.rs (hunk 2 above)
Comment (tomgs) [reply localdev/dummy.rs]: This is now irrelevant since I no longer need a `dummy.rs` file at all, resolving.

File: localdev/Dockerfile (hunk 6 above)
Comment (tomgs) [reply localdev/Dockerfile]: Resolving since we're not using a `dummy.rs` file anymore.

File: Makefile [hunk 7]
```diff
@@ -1,50 +1,76 @@
...
-tag-latest:
+tag-latest: ## tags the latest container with the version listed above
 	@echo 'create tag latest'
-	docker tag $(DOCKER_REPO)/$(APP_NAME):$(VERSION) $(DOCKER_REPO)/$(APP_NAME):latest
+	docker tag $(DOCKER_REMOTE_REPO)/$(APP_NAME):$(VERSION) $(DOCKER_REMOTE_REPO)/$(APP_NAME):latest
 
 version: ## output to version
-	@echo $(VERSION)
\ No newline at end of file
+	@echo ''$(VERSION)
```
Comment (FedericoPonzi) [inline Makefile:50]: Typo?

File: Makefile [hunk 8]
```diff
@@ -1,50 +1,76 @@
...
+	make dargo COMMAND=test
+	# Now all caches are filled, and subsequent operations will be faster
+	# Consider adding dargo(){ make dargo COMMAND=$1} to your ~/.zshrc or ~/.bashrc for ergonomics
+
+dargo: ## Run a cargo command inside the container
+	docker exec -ti docker-horust cargo $(COMMAND)
+
+dargo-create-container: ## Create a Rust container with this folder bind-mounted to it
+	@echo 'building rust image for local development'
+	docker build -t horust -f localdev/Dockerfile localdev/
```
Comment (FedericoPonzi) [inline Makefile:71]: You can skip this step because we can just use rust:1.42 as image instead of this one.

File: Makefile [hunk 9]
```diff
@@ -1,50 +1,76 @@
...
+	@echo 'running interactive rust container for local development'
+	docker run -dt \
+ 	--name docker-horust \
+ 	--mount type=bind,source="$(shell pwd)",target=/usr/src/Horust \
```
Comment (FedericoPonzi) [inline Makefile:75]: Is there a makefile command to get the makefile path? Because I would use that instead of pwd. Otherwise, please specify in the docs to CD to the horust home dir...

File: Makefile [hunk 10]
```diff
@@ -1,50 +1,76 @@
...
+	docker tag $(DOCKER_REMOTE_REPO)/$(APP_NAME):$(VERSION) $(DOCKER_REMOTE_REPO)/$(APP_NAME):latest
 
 version: ## output to version
-	@echo $(VERSION)
\ No newline at end of file
+	@echo ''$(VERSION)
+
+# Docker local development tasks
+## Dargo == Docker Cargo
+dargo-prep: ## This runs everything neccessary to start developing locally in a container
```
Comment (FedericoPonzi) [inline Makefile:54]: If inside dargo you add a check for the running container instance, one can just use that instead from the first run .

File: Makefile [hunk 11]
```diff
@@ -1,50 +1,76 @@
...
+
+dargo: ## Run a cargo command inside the container
+	docker exec -ti docker-horust cargo $(COMMAND)
+
+dargo-create-container: ## Create a Rust container with this folder bind-mounted to it
+	@echo 'building rust image for local development'
+	docker build -t horust -f localdev/Dockerfile localdev/
+	@echo 'running interactive rust container for local development'
+	docker run -dt \
+ 	--name docker-horust \
```
Comment (FedericoPonzi) [inline Makefile:74]: This belongs to a variable

**Comment by FedericoPonzi** [comment]
The ux is even better than I could imagine, silly me was thinking of keeping a terminal opened inside the container but your solution is actually a lot magical and better eheh. I think that with some checks we can further simplify the flow.

File: Makefile (hunk 7 above)
Comment (tomgs) [reply Makefile:50]: Oh yes, very much so - fixed

File: localdev/Dockerfile (hunk 1 above)
Comment (tomgs) [reply localdev/Dockerfile]: Irrelevant, resolving

File: localdev/Dockerfile (hunk 6 above)
Comment (tomgs) [reply localdev/Dockerfile]: Irrelevant, resolving

File: localdev/dummy.rs (hunk 2 above)
Comment (tomgs) [reply localdev/dummy.rs]: Resolving

File: Makefile (hunk 8 above)
Comment (tomgs) [reply Makefile:71]: But I'd like to set the `WORKDIR` to `/usr/src/Horust` instead of `/` and have the `CMD` set to `/bin/bash`. That `localdev/Dockerfile` now is just:


```Dockerfile
FROM rust:1.42
WORKDIR /usr/src/Horust
CMD ["/bin/bash"]
```

If you look [here](https://github.com/rust-lang/docker-rust/blob/8bab191937fcf23569d3a3c31103c1c6f7f2947e/1.42.0/buster/Dockerfile), the original `rust:1.42` Dockerfile does neither.

Or am I missing something?

Comment (FedericoPonzi) [reply Makefile:71]: You can pass those as parameters of docker run. https://docs.docker.com/engine/reference/run/#workdir
So docker run -d rust:142 -w .... /bin/bash

File: Makefile (hunk 9 above)
Comment (tomgs) [reply Makefile:75]: I actually do specify it in the docs:)

https://github.com/FedericoPonzi/Horust/pull/41/files#diff-6a3371457528722a734f3c51d9238c13R99-R102

File: Makefile (hunk 10 above)
Comment (tomgs) [reply Makefile:54]: What does a "check for the running container instance" mean exactly?

File: Makefile (hunk 11 above)
Comment (tomgs) [reply Makefile:74]: That it does. Adding now

File: Makefile (hunk 8 above)
Comment (tomgs) [reply Makefile:71]: True, testing now

File: Makefile (hunk 9 above)
Comment (tomgs) [reply Makefile:75]: I could use something like [this](https://stackoverflow.com/a/18137056/491214), but it feels a bit convoluted. I like `cd` into a place and do X Y Z better

File: Makefile (hunk 8 above)
Comment (tomgs) [reply Makefile]: Only flags now, deleting the localdev folder

File: Makefile (hunk 10 above)
Comment (FedericoPonzi) [reply Makefile:56]: Sorry I was from the phone! I meant the following: instead of doing dargo-create-container and then calling dargo as a two step thing, you could reduce it to a single step thing in the following way.
on line 69, when a user calls `dargo test`, before calling docker exec, you can do 
```
if docker ps | grep LOCAL_DEV_CONTAINER_NAME is empty { 
docker run [...} 
}
docker exec ...
}
```
The first time you use dargo x, it will not find the running instance thus it will first spawn it and then run your command
The second time you use dargo x, it will find the running instance and just use that. So you're basically adding a check for the running instance (paying a bit of delay time for this check) but improving the ux.

File: Makefile [hunk 12]
```diff
@@ -1,50 +1,79 @@
...
+# Docker local development tasks
+## Dargo == Docker Cargo
+dargo-prep: ## This runs everything neccessary to start developing locally in a container
+	# Spin up a long-running rust container
+	make dargo-create-container
+	# Compile and cache all dependencies
+	make dargo COMMAND=build
+	# Perform a first-sweep check, to fill up the cache (it seems to be different than the build one)
+	make dargo COMMAND=check
+    # Compile and cache test dependencies, run tests
```
Comment (FedericoPonzi) [inline Makefile:63]: add a space c:

File: Makefile (hunk 10 above)
Comment (tomgs) [reply Makefile:56]: Ah, that's pretty neat, kinda like what `docker run X` does when it doesn't find `X` locally (i.e. pull it from dockerhub).
Implementing now

File: Makefile (hunk 12 above)
Comment (tomgs) [reply Makefile]: You got it bro

**Comment by tomgs** [comment]
You get a dargo, you get a dargo, everyone gets a dargo! :)

File: Makefile [hunk 13]
```diff
@@ -54,23 +54,26 @@ version: ## output to version
...
 	# Now all caches are filled, and subsequent operations will be faster
 	# Consider adding dargo(){ make dargo COMMAND=$1} to your ~/.zshrc or ~/.bashrc for ergonomics
 
 dargo: ## Run a cargo command inside the container
+	@# If the dargo container does not exist, create it
+	@if [ -z $(shell docker ps | grep "$(LOCAL_DEV_CONTAINER_NAME)" | cut -c1-12) ]; then make dargo-prep; fi
+	@# Run a command inside the container
 	docker exec -ti $(LOCAL_DEV_CONTAINER_NAME) cargo $(COMMAND)
 
 dargo-create-container: ## Create a Rust container with this folder bind-mounted to it
```
Comment (FedericoPonzi) [inline Makefile:74]:
```suggestion
dargo-run-container: ## Runs a Rust container with cwd folder bind-mounted to it
```

File: Makefile [hunk 14]
```diff
@@ -54,23 +54,26 @@ version: ## output to version
...
+	@# Perform a first-sweep check, to fill up the cache (it seems to be different than the build one)
+	@make dargo COMMAND=check
+	@# Compile and cache test dependencies, run tests
+	@make dargo COMMAND=test
 	# Now all caches are filled, and subsequent operations will be faster
 	# Consider adding dargo(){ make dargo COMMAND=$1} to your ~/.zshrc or ~/.bashrc for ergonomics
 
 dargo: ## Run a cargo command inside the container
+	@# If the dargo container does not exist, create it
+	@if [ -z $(shell docker ps | grep "$(LOCAL_DEV_CONTAINER_NAME)" | cut -c1-12) ]; then make dargo-prep; fi
```
Comment (FedericoPonzi) [inline Makefile:70]: You can simplify these pipes to a single docker ps call: `docker ps --format "{{.ID}}" --filter "name=$(LOCAL_DEV_CONTAINER_NAME"`

File: CONTRIBUTING.md [hunk 15]
```diff
@@ -60,8 +60,63 @@ make help
...
+Just to make sure everything is clear, let's run a step-by-step mini tutorial on developing in container-based workflow "mode":
+
+1. Clone the repo to your local machine:
+```shell 
+git clone https://github.com/FedericoPonzi/Horust.git`
+cd Horust
+```
+2. Create the AIO container (can take a while):
+```shell
+make dargo-prep
```
Comment (FedericoPonzi) [inline CONTRIBUTING.md:106]: Do we really need this step?

File: CONTRIBUTING.md [hunk 16]
```diff
@@ -60,8 +60,63 @@ make help
...
+``` 
+3. Add "alias" to `make dargo COMMAND=X`:
```
Comment (FedericoPonzi) [inline CONTRIBUTING.md:108]: I would move it at the bottom as a suggested improvement for the workflow, it's not really mandatory required (and people not familiar with it or running another shell might get a different result)

Comment (FedericoPonzi) [reply CONTRIBUTING.md:108]: I just saw that you already wrote this on the previous paragraph. Then I think this step can be removed without arm, you might want to add a note at step 5 for the aliasing.

File: Makefile (hunk 13 above)
Comment (tomgs) [reply Makefile:74]: cwd == pwd?

File: Makefile (hunk 14 above)
Comment (tomgs) [reply Makefile:70]: Docker has go template-style formatting to the output? Cool! And also filtering? Dope! :)

File: CONTRIBUTING.md (hunk 15 above)
Comment (tomgs) [reply CONTRIBUTING.md:106]: I need to update the docs actually

File: Makefile (hunk 13 above)
Comment (FedericoPonzi) [reply Makefile:74]: No, I really meant cwd as in "current working directory"

File: Makefile (hunk 10 above)
Comment (tomgs) [reply Makefile:56]: Done

File: CONTRIBUTING.md (hunk 15 above)
Comment (tomgs) [reply CONTRIBUTING.md:106]: Done

File: CONTRIBUTING.md (hunk 16 above)
Comment (tomgs) [reply CONTRIBUTING.md:108]: Re-wrote the thing, take a look?

Comment (tomgs) [reply CONTRIBUTING.md:108]: Re-wrote the thing, take a look?

File: Makefile (hunk 13 above)
Comment (tomgs) [reply Makefile]: Well, pwd is present working directory, and the command is pwd...

File: Makefile [hunk 17]
```diff
@@ -1,50 +1,82 @@
...
+	@# Perform a first-sweep check, to fill up the cache (it seems to be different than the build one)
+	@make dargo COMMAND=check
+	@# Compile and cache test dependencies, run tests
+	@make dargo COMMAND=test
+	# Now all caches are filled, and subsequent operations will be faster
+	# Consider adding dargo(){ make dargo COMMAND=$1} to your ~/.zshrc or ~/.bashrc for ergonomics
+
+dargo: ## Run a cargo command inside the container
+	@# If the dargo container does not exist, create it
+	@if [ -z $(shell docker ps --format "{{.ID}}" --filter "name=$(LOCAL_DEV_CONTAINER_NAME)") ]; then make dargo-prep; fi
```
Comment (FedericoPonzi) [inline Makefile:70]: I'm probably missing something, but in my comment above ^ I was also suggesting to remove the dargo-prep altogether, and call dargo-run-container instead. The cache thing made sense in the previous "version" maybe, in this case if the user either runs cargo test / build /check  which is going to download dependencies anyway. In the same way, when you download any rust project for the first time you don't need to run check / build / test, I think we should just remove the dargo-prep command if there is no good reason for keeping it.

Comment (tomgs) [reply Makefile:70]: Ahh.... yeah I see it now. Replacing

**Comment by tomgs** [comment]
Com'on, let's mergie-merge this today

File: Makefile (hunk 13 above)
Comment (FedericoPonzi) [reply Makefile]: According to `man pwd` stands for print current working directory, and `cwd` as a name is a thing in linux:
https://linux.die.net/man/3/cwd
I would read it as "Runs a Rust container with print current working directory folder bind...."
Well, actually `current working directory folder` doesn't reads much right as well ahah :D

File: CONTRIBUTING.md [hunk 18]
```diff
@@ -73,16 +73,14 @@ If this is the first time you run the command, it will:
 
 1. Create a Docker image with a pre-determined working directory
 2. Run an (interactive / long-running) container off that image, with the local Horust project folder bind-mounted to the working directory
-3. Compile Horust and all its dependencies inside the container, using the local folder as storage for the cache
-4. Compile test dependencies and fill a few more caches (using `cargo test` and `cargo check`)
 5. Run `cargo X` inside the container
```
Comment (FedericoPonzi) [inline CONTRIBUTING.md:76]:
```suggestion
3. Run `cargo X` inside the container
```

File: DOCUMENTATION.md [hunk 19]
```diff
@@ -130,7 +130,7 @@ die-if-failed = ["db.toml"]
 ---
 
 ## State machine
-[![State machne](https://github.com/FedericoPonzi/Horust/raw/master/res/state-machine.png)](https://github.com/FedericoPonzi/Horust/raw/master/res/state-machine.png)
+[![State machine](https://github.com/FedericoPonzi/Horust/raw/master/res/state-machine.png)](https://github.com/FedericoPonzi/Horust/raw/master/res/state-machine.png)
```
Comment (FedericoPonzi) [inline DOCUMENTATION.md:133]: good catch!

File: Makefile (hunk 13 above)
Comment (tomgs) [reply Makefile]: Lol gonna make it cwd to make you happy and be done with it
